CANONICAL_CATEGORIES = [
    "Casual",
    "Puzzle",
    "Adventure",
    "Racing & Driving",
    "Simulation",
    "Dress-up",
    "Agility",
    "Shooter",
    "Battle",
    "Match-3",
    "Strategy",
    "Mahjong & Connect",
    ".IO",
    "Art",
    "Merge",
    "Sports",
    "Cards",
    "Educational",
    "Bubble Shooter",
    "Football",
    "Cooking",
    "Care",
    "Boardgames",
    "Basketball",
    "Quiz",
    "Jigsaw",
]
